<?php
$CONFIG = array(
	'instanceid' => 'oct2fzrutjet',
	'passwordsalt' => 'Zjv7b8Nl2vi5bKTZBHV6rgsUR+O8FA',
	'secret' => 'Ao3Bh0L8bQ2n+MTmmAlWNYljVsUiNLCfceRwIn1Y+oASkrFw',
	'trusted_domains' =>
		array(
			'nextcloud.service.gongt.me:59443',
		),
	'datadirectory' => '/drives/AppData/NextCloud',
	'dbtype' => 'mysql',
	'dbhost' => 'localhost:/var/run/socket/mysqld/mysql.sock',
	'dbname' => 'nextcloud',
	'dbuser' => 'nextcloud',
	'dbpassword' => 'nextcloud',
	'dbtableprefix' => 'nc_',
	'mysql.utf8mb4' => true,
	'default_language' => 'zh_CN',
	'default_locale' => 'zh_CN',
	'knowledgebaseenabled' => false,
	'remember_login_cookie_lifetime' => 60 * 60 * 24 * 30,
	'session_lifetime' => 60 * 60 * 24 * 30,
	'session_keepalive' => false,
	'token_auth_enforced' => false,
	'mail_domain' => 'gongt.me',
	'mail_smtpmode' => 'smtp',
	'mail_smtpname' => 'NextCloud Notify',
	'mail_from_address' => 'nextcloud@gongt.me',
	'mail_smtppassword' => '5dlLo5xY2Xg8tmOU2EAQ',
	'mail_smtphost' => 'smtp.mailgun.org',
	'mail_smtpsecure' => 'tls',
	'mail_smtpport' => 587,
	'mail_smtptimeout' => 30,
	'mail_smtpauth' => true,
	'mail_smtpauthtype' => 'LOGIN',
	'overwriteprotocol' => 'https',
	'proxy' => '10.0.0.1:3271',
	'trashbin_retention_obligation' => '7,30',
	'connectivity_check_domains' => array('google.com'),
	'check_for_working_htaccess' => false,
	'log_type' => 'systemd',
	'logfile' => '/var/log/nextcloud/nextcloud.log',
	'logfilemode' => 0644,
	'syslog_tag' => 'nextcloud',
	'logdateformat' => 'Y-M-d H:i:s',
	'logtimezone' => 'Asia/Shanghai',
	'enable_previews' => true,
	'enabledPreviewProviders' => array(
		'OC\Preview\Illustrator',
		'OC\Preview\OpenDocument',
		'OC\Preview\PDF',
		'OC\Preview\SVG',
		'OC\Preview\Font',
		'OC\Preview\PNG',
		'OC\Preview\JPEG',
		'OC\Preview\GIF',
		'OC\Preview\HEIC',
		'OC\Preview\BMP',
		'OC\Preview\XBitmap',
		'OC\Preview\MP3',
		'OC\Preview\TXT',
		'OC\Preview\MarkDown'
	),
	'memcache.local' => '\OC\Memcache\APCu',
	'memcache.locking' => '\OC\Memcache\Redis',
	'redis' => [
		'host' => '/var/run/redis/cache/redis.sock', // can also be a unix domain socket: '/tmp/redis.sock'
		'port' => 0,
		'dbindex' => 0,
		'timeout' => 1.5,
	],
	'memcached_servers' => [
		['127.0.0.1', 11212],
	],
	'memcached_options' => array(
		// Set timeouts to 50ms
		\Memcached::OPT_CONNECT_TIMEOUT => 50,
		\Memcached::OPT_RETRY_TIMEOUT => 50,
		\Memcached::OPT_SEND_TIMEOUT => 50,
		\Memcached::OPT_RECV_TIMEOUT => 50,
		\Memcached::OPT_POLL_TIMEOUT => 50,
		\Memcached::OPT_COMPRESSION => true,
		\Memcached::OPT_LIBKETAMA_COMPATIBLE => true,
		\Memcached::OPT_BINARY_PROTOCOL => true,
		\Memcached::OPT_SERIALIZER => \Memcached::SERIALIZER_IGBINARY,
	),
	'blacklisted_files' => array(
		'.htaccess',
		'.recycle',
		'$RECYCLE.BIN',
		'found.000',
		'System Volume Information',
		'OneDriveTemp',
		'thumbs.db'
	),
	'version' => '15.0.5.3',
	'overwrite.cli.url' => 'https://nextcloud.service.gongt.me:59443',
	'installed' => true,
	'config_is_read_only' => true,
	
	'debug' => true,
);

